spring.application.name=vacinas

spring.datasource.url=jdbc:mysql://localhost:3306/vacinacao?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver